baseURL: "https://markphilpot.com"
languageCode: en-us
title: mark philpot
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

permalinks:
  page:
    blog: /posts/:year/:month/:day/:slug

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    - name: µposts
      url: https://micro.markphilpot.com
    - name: about
      url: about
      weight: 2
    - name: social
      url: https://philpot.org/@mark
    - name: ~/projects
      url: projects
      weight: 3
    # - name: archive
    #   url: archives
    - name: search
      url: search
      weight: 1

params:
  disableThemeToggle: true
  ShowReadingTime: false
  disableScrollToTop: true
  ShowPostNavLinks: true
