baseURL: "https://markphilpot.com"
languageCode: en-us
title: mark philpot
theme: PaperModX
timeout: 100s

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

permalinks:
  page:
    blog: /posts/:year/:month/:day/:slug

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    - name: about
      url: about
      weight: 1
    - name: ~/projects
      url: projects
      weight: 1
    # - name: archive
    #   url: archives
    #   weight: 2
    # - name: tags
    #   url: tags
    #   weight: 3
    - name: search
      url: search
      weight: 4

params:
  disableThemeToggle: true
  ShowReadingTime: true
  disableScrollToTop: false
  ShowPostNavLinks: true
  assets:
    favicon: "/assets/favicon/favicon.ico"
    favicon16x16: "/assets/favicon/favicon-16x16.png"
    favicon32x32: "/assets/favicon/favicon-32x32.png"
    apple_touch_icon: "/assets/favicon/apple-touch-icon.png"
    safari_pinned_tab: "/assets/favicon/safari-pinned-tab.svg"
