baseURL: "https://markphilpot.com"
languageCode: en-us
title: mark philpot
theme: PaperModX
timeout: 500s

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
capitalizeListTitles: false

permalinks:
  page:
    blog: /posts/:year/:month/:day/:slug
    micro: /micro/:year/:month/:day/:slugorfilename

services:
  rss:
    limit: 42

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false

outputs:
  home:
    - HTML
    - RSS
    - ATOM
    - JSON # is necessary

mediaTypes:
  application/atom+xml:
    suffixes:
      - xml

outputFormats:
  atom:
    mediaType: "application/atom+xml"
    baseName: "atom"
    suffix: "xml"
    isHTML: false
    isPlainText: false
    noUgly: true
    rel: "alternate"

menu:
  main:
    - name: essays
      url: /blog
      weight: 1
    - name: ~/projects
      url: /projects
      weight: 10
    # - name: /micro
    #   url: https://micro.markphilpot.com
    #   weight: 20
    #   params:
    #     external: true
    - name: /now
      url: /now
      weight: 30
    - name: /about
      url: /about
      weight: 40
    # - name: archive
    #   url: archives
    #   weight: 2
    # - name: tags
    #   url: tags
    #   weight: 3
    - name: /search
      pageRef: /search

params:
  disableThemeToggle: true
  ShowReadingTime: true
  disableScrollToTop: false
  ShowPostNavLinks: true
  assets:
    favicon: "/assets/favicon/favicon.ico"
    favicon16x16: "/assets/favicon/favicon-16x16.png"
    favicon32x32: "/assets/favicon/favicon-32x32.png"
    apple_touch_icon: "/assets/favicon/apple-touch-icon.png"
    safari_pinned_tab: "/assets/favicon/safari-pinned-tab.svg"
  mainSections:
    - blog
    - micro

  editPost:
    URL: "https://github.com/markphilpot/markphilpot_com_hugo/tree/main/content"
    Text: "⑆" # edit text
    appendFilePath: true # to append file path to Edit link
